import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const inter = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: "Prajwal's portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Add the link tag for the favicon here */}
        <link rel="icon" href="/prajwalicon.png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
